# Generated by Django 6.1.1 on 2026-09-30 12:39

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCustomer',
            fields=[
            ],
            options={
                'permissions': [('view_customers', 'Can view customers'), ('change_customers', 'Can change customer accounts')],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
