# Generated by Django 6.1.1 on 2026-09-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catageory',
            new_name='category',
        ),
    ]
